import pandas as pd
from gensim import corpora
from gensim.models import LdaMulticore
import os
import sys

# Add root directory to sys.path to import config
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from config import DATA_PROCESSED, DATA_RESULTS

# --- CONFIGURATION ---
INPUT_PROCESSED_CSV = os.path.join(DATA_PROCESSED, "dati_testuali_preproc_consolidati.csv")
COLONNA_TESTO_PROCESSATO = "testo_lemmatizzato"
COLONNA_LINGUA = "lingua_rilevata"

# Output files
OUTPUT_TOPICS_EN = os.path.join(DATA_RESULTS, "lda_topics_en.txt")
OUTPUT_DOC_TOPICS_EN = os.path.join(DATA_RESULTS, "document_topics_en.csv")
OUTPUT_TOPICS_IT = os.path.join(DATA_RESULTS, "lda_topics_it.txt")
OUTPUT_DOC_TOPICS_IT = os.path.join(DATA_RESULTS, "document_topics_it.csv")

# Hyperparameters
LDA_PASSES = 20
LDA_WORKERS = 7  # Optimized for Ryzen 7 (8 cores / 16 threads)

# Check for optimal k (generated by 03_coherence.py)
def load_optimal_k(lingua):
    import json
    path = os.path.join(DATA_RESULTS, f"optimal_k_{lingua.lower()}.json")
    if os.path.exists(path):
        with open(path, 'r') as f:
            data = json.load(f)
            print(f"[{lingua.upper()}] Optimal k found: {data['optimal_k']} (Cv={data['max_cv']:.4f})")
            return data['optimal_k']
    print(f"[{lingua.upper()}] Optimal k not found. Using default k=15")
    return 15

# The final model uses the coherence-optimal k computed by 03_coherence.py on the
# SAME dictionary (filter_extremes no_below=5, no_above=0.5), so coherence analysis
# and final model are guaranteed to be consistent.
NUM_TOPICS_EN = load_optimal_k("en")
NUM_TOPICS_IT = load_optimal_k("it")

# --- SPACY MODELS (Required for final verification) ---
import spacy
try:
    nlp_en = spacy.load("en_core_web_sm")
    print("English spaCy model (en_core_web_sm) loaded.")
except:
    print("ERROR: English spaCy model 'en_core_web_sm' not found.")
    nlp_en = None

try:
    nlp_it = spacy.load("it_core_news_sm")
    print("Italian spaCy model (it_core_news_sm) loaded.")
except:
    print("ERROR: Italian spaCy model 'it_core_news_sm' not found.")
    nlp_it = None

if not nlp_en and not nlp_it:
    print("\nCRITICAL ERROR: No spaCy models loaded. Cannot proceed.")
    sys.exit(1)

# --- FUNCTIONS ---

def prepara_corpus_per_lda(documenti_testuali):
    """
    Prepares data for Gensim LDA: tokenizes, creates dictionary and BoW corpus.
    documenti_testuali: a list of strings (lemmatized docs, space-separated tokens) or list of lists.
    """
    # If documents are already lists of tokens, use them directly
    if len(documenti_testuali) > 0 and isinstance(documenti_testuali[0], list):
        tokenized_docs = documenti_testuali
    else:
        print("  Tokenizing documents (split by space)...")
        tokenized_docs = [doc.split() for doc in documenti_testuali if isinstance(doc, str) and doc.strip()]
    
    if not tokenized_docs:
        print("  No valid documents after preliminary tokenization.")
        return None, None, None

    print("  Creating Gensim dictionary...")
    dictionary = corpora.Dictionary(tokenized_docs)
    # Filter extremes to match 03_coherence.py
    dictionary.filter_extremes(no_below=5, no_above=0.5)
    print(f"    Dictionary created with {len(dictionary)} unique tokens.")

    print("  Creating Bag-of-Words corpus...")
    corpus_bow = [dictionary.doc2bow(doc) for doc in tokenized_docs]
    print(f"    BoW corpus created for {len(corpus_bow)} documents.")
    
    return tokenized_docs, dictionary, corpus_bow

def get_dominant_topic(lda_model, bow_corpus):
    """
    Extracts the dominant topic for each document in the corpus.
    """
    dominant_topics = []
    for i, row in enumerate(lda_model[bow_corpus]):
        # Sort topics by probability
        row = sorted(row, key=lambda x: (x[1]), reverse=True)
        if row:
            topic_num, prop_topic = row[0]
            dominant_topics.append(int(topic_num))
        else:
            dominant_topics.append(None)
    return dominant_topics

# --- MAIN EXECUTION ---

if __name__ == "__main__":
    print(f"Loading pre-processed data from: {INPUT_PROCESSED_CSV}")
    try:
        df_processed = pd.read_csv(INPUT_PROCESSED_CSV, low_memory=False)
        print(f"Loaded {len(df_processed)} rows of pre-processed data.")
    except FileNotFoundError:
        print(f"ERROR: File '{INPUT_PROCESSED_CSV}' not found.")
        sys.exit(1)

    # Clean missing values in the processed text column
    df_processed[COLONNA_TESTO_PROCESSATO] = df_processed[COLONNA_TESTO_PROCESSATO].astype(str)
    df_processed = df_processed[df_processed[COLONNA_TESTO_PROCESSATO].str.strip() != '']
    print(f"Rows after removing empty texts: {len(df_processed)}")

    # --- ENGLISH ---
    if nlp_en:
        print("\n--- Starting Topic Modeling for ENGLISH texts ---")
        df_en = df_processed[df_processed[COLONNA_LINGUA] == 'en'].copy()
        
        if df_en.empty:
            print("No English documents found for Topic Modeling.")
        else:
            # Filter out documents that become empty after split (e.g., only stopwords/symbols)
            df_en['temp_tokens'] = df_en[COLONNA_TESTO_PROCESSATO].fillna('').astype(str).str.split()
            df_en = df_en[df_en['temp_tokens'].map(len) > 0].copy()
            tokenized_docs_en = df_en['temp_tokens'].tolist()
            del df_en['temp_tokens']
            
            if not tokenized_docs_en:
                print("No valid English documents after tokenization.")
            else:
                _, dictionary_en, corpus_bow_en = prepara_corpus_per_lda(tokenized_docs_en)

            if tokenized_docs_en and dictionary_en and corpus_bow_en:
                print(f"\nTraining LDA model for English with {NUM_TOPICS_EN} topics...")
                lda_model_en = LdaMulticore(
                    corpus=corpus_bow_en,
                    id2word=dictionary_en,
                    num_topics=NUM_TOPICS_EN,
                    random_state=100,
                    passes=LDA_PASSES,
                    workers=LDA_WORKERS
                )
                print("English LDA model trained.")

                # Save topics and keywords
                print("\nIdentified English Topics (top words per topic):")
                with open(OUTPUT_TOPICS_EN, "w", encoding="utf-8") as f:
                    for idx, topic in lda_model_en.print_topics(-1):
                        print(f"Topic EN #{idx}: {topic}")
                        f.write(f"Topic EN #{idx}: {topic}\n")
                print(f"English topics saved to '{OUTPUT_TOPICS_EN}'")

                # Assign dominant topics to documents
                print("\nAssigning dominant topics to English documents...")
                dominant_topics_en = get_dominant_topic(lda_model_en, corpus_bow_en)
                
                if len(dominant_topics_en) == len(df_en):
                    df_en['topic_dominante_en'] = dominant_topics_en
                    df_en.to_csv(OUTPUT_DOC_TOPICS_EN, index=False)
                    print(f"Dominant topics for English documents saved to '{OUTPUT_DOC_TOPICS_EN}'")
                else:
                    print(f"ERROR: mismatch in number of dominant topics EN ({len(dominant_topics_en)}) and documents EN ({len(df_en)}).")
            else:
                print("Corpus preparation failed for English texts.")

    # --- ITALIAN ---
    if nlp_it:
        print("\n--- Starting Topic Modeling for ITALIAN texts ---")
        df_it = df_processed[df_processed[COLONNA_LINGUA] == 'it'].copy()
        
        if df_it.empty:
            print("No Italian documents found for Topic Modeling.")
        else:
            # Filter out documents that become empty after split
            df_it['temp_tokens'] = df_it[COLONNA_TESTO_PROCESSATO].fillna('').astype(str).str.split()
            df_it = df_it[df_it['temp_tokens'].map(len) > 0].copy()
            tokenized_docs_it = df_it['temp_tokens'].tolist()
            del df_it['temp_tokens']

            if not tokenized_docs_it:
                 print("No valid Italian documents after tokenization.")
            else:
                _, dictionary_it, corpus_bow_it = prepara_corpus_per_lda(tokenized_docs_it)

            if tokenized_docs_it and dictionary_it and corpus_bow_it:
                print(f"\nTraining LDA model for Italian with {NUM_TOPICS_IT} topics...")
                lda_model_it = LdaMulticore(
                    corpus=corpus_bow_it,
                    id2word=dictionary_it,
                    num_topics=NUM_TOPICS_IT,
                    random_state=100,
                    passes=LDA_PASSES,
                    workers=LDA_WORKERS
                )
                print("Italian LDA model trained.")

                # Save topics and keywords
                print("\nIdentified Italian Topics (top words per topic):")
                with open(OUTPUT_TOPICS_IT, "w", encoding="utf-8") as f:
                    for idx, topic in lda_model_it.print_topics(-1):
                        print(f"Topic IT #{idx}: {topic}")
                        f.write(f"Topic IT #{idx}: {topic}\n")
                print(f"Italian topics saved to '{OUTPUT_TOPICS_IT}'")

                # Assign dominant topics to documents
                print("\nAssigning dominant topics to Italian documents...")
                dominant_topics_it = get_dominant_topic(lda_model_it, corpus_bow_it)
                
                if len(dominant_topics_it) == len(df_it):
                    df_it['topic_dominante_it'] = dominant_topics_it
                    df_it.to_csv(OUTPUT_DOC_TOPICS_IT, index=False)
                    print(f"Dominant topics for Italian documents saved to '{OUTPUT_DOC_TOPICS_IT}'")
                else:
                    print(f"ERROR: mismatch in number of dominant topics IT ({len(dominant_topics_it)}) and documents IT ({len(df_it)}).")
            else:
                print("Corpus preparation failed for Italian texts.")

    print("\nTopic Modeling script finished.")